---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2020
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

linters:
  enable-all: true
  disable:
    - interfacer  # Deprecated (since v1.38.0) due to: The repository of the linter has been archived by the owner.
    - golint  # Deprecated (since v1.41.0) due to: The repository of the linter has been archived by the owner.  Replaced by revive.
    - scopelint  # Deprecated (since v1.39.0) due to: The repository of the linter has been deprecated by the owner.  Replaced by exportloopref.
    - maligned  # Deprecated (since v1.38.0) due to: The repository of the linter has been archived by the owner.  Replaced by govet 'fieldalignment'.
    - exhaustivestruct  # Deprecated (since v1.46.0) due to: The owner seems to have abandoned the linter.  Replaced by exhaustruct.
