---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2020
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

language: bash
os: linux
git:
  depth: 1
dist: bionic
cache:
  directories:
    - /home/travis/.vagrant.d/boxes
before_install:
  - sudo apt update
  - sudo apt-get install -y -qq -o=Dpkg::Use-Pty=0 --no-install-recommends curl
jobs:
  include:
    - name: Lint validation
      install:
        - curl -fsSL http://bit.ly/install_pkg | PKG="tox hadolint" bash
      script:
        - tox -v -e lint
        - find . -type f -iname "*sh" -exec shellcheck -x {} \;
        - find . -type f -iname "*Dockerfile*" -exec hadolint {} \;
    - name: Ubuntu 20.04 LTS Vagrant validation
      install:
        - sudo apt-get install -y -qq -o=Dpkg::Use-Pty=0 --no-install-recommends qemu
        - curl -fsSL http://bit.ly/initVagrant | PROVIDER=libvirt bash
      script:
        - sudo -E vagrant up
