---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2021
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

name: Check End-to-End (On Demand)
# yamllint disable-line rule:truthy
on:
  push:
    paths:
      - '**.go'
      - '**.yml'
      - '**.sh'
      - '!.github/*'
  pull_request_review:
    types:
      - submitted

jobs:
  unit-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.3'
      - uses: haveyoudebuggedit/gotestfmt-action@v2
      - name: Run tests
        run: |
          set -euo pipefail
          go test -json -v ./... 2>&1 | tee /tmp/gotest.log | gotestfmt
      - name: Upload test log
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: test-log
          path: /tmp/gotest.log
          if-no-files-found: error
  functional-test:
    runs-on: ubuntu-20.04
    env:
      DEBUG: true
    steps:
      - uses: actions/checkout@v3
      - name: Run assertions
        run: |
          ./scripts/integration_test.sh
  system-test:
    runs-on: ubuntu-20.04
    env:
      DEBUG: true
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: ./scripts/install.sh
      - name: Deploy services
        run: ./scripts/deploy.sh
      - name: Deploy demo app
        run: ./scripts/check.sh
