---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2021
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

name: Check End-to-End (On Demand)
# yamllint disable-line rule:truthy
on:
  push:
    paths:
      - '**.go'
      - '**.yml'
      - '**.sh'
      - '!.github/*'
  pull_request_review:
    types:
      - submitted

jobs:
  check-ci-baremetal:
    runs-on: ubuntu-20.04
    env:
      DEBUG: true
    steps:
      - uses: actions/checkout@v2
      - name: Deploy services
        run: |
          ./scripts/install.sh
          ./scripts/deploy.sh
          ./scripts/check.sh
