# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2021
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
name: Check End-to-End (On Demand)
# yamllint disable-line rule:truthy
on:
  push:
    paths:
      - "**.go"
      - "**.yml"
      - "**.sh"
      - "!.github/*"
  pull_request_review:
    types:
      - submitted
jobs:
  check-format:
    name: Check scripts format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2
      - name: Run the sh-checker
        uses: luizm/action-sh-checker@17bd25a6ee188d2b91f677060038f4ba37ba14b2 # 0.9.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHFMT_OPTS: -i 4 -s
        with:
          sh_checker_shellcheck_disable: true
  functional-test:
    name: Check functional tests
    runs-on: ubuntu-20.04
    env:
      DEBUG: true
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2
      - name: Run assertions
        run: |
          ./scripts/integration_test.sh
  system-test:
    name: Check system tests
    runs-on: ubuntu-20.04
    env:
      DEBUG: true
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2
      - name: Install dependencies
        run: ./scripts/install.sh
      - name: Deploy services
        run: ./scripts/deploy.sh
      - name: Deploy demo app
        run: ./scripts/check.sh
