---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2021
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

name: Check Go Lang tests (On Demand)
# yamllint disable-line rule:truthy
on:
  push:
    paths:
      - '**.go'
  pull_request_review:
    types:
      - submitted

jobs:
  unit-test:
    name: Check Go lang unit tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.17.3'
      - uses: actions/cache@v4
        if: ${{ !env.ACT }}
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - uses: haveyoudebuggedit/gotestfmt-action@v2
      - name: Run tests
        run: |
          set -euo pipefail
          go test -json -v ./... 2>&1 | tee /tmp/gotest.log | gotestfmt
      - name: Upload test log
        uses: actions/upload-artifact@v4
        if: ${{ !env.ACT }}
        with:
          name: test-log
          path: /tmp/gotest.log
          if-no-files-found: error
