# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2021
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
name: Scheduled Versions verification
# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:
jobs:
  check-versions:
    permissions:
      contents: write # for technote-space/create-pr-action to push code
      pull-requests: write # for technote-space/create-pr-action to create a PR
    runs-on: vm-self-hosted
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2
        with:
          # Fine-grained PAT with contents:write and workflows:write scopes
          token: ${{ secrets.WORKFLOW_TOKEN }}
      - uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # 5.3.0
        with:
          python-version: "^3.10"
      - uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # 5.2.0
        with:
          go-version: "^1.20"
      - uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # 4.2.0
        with:
          node-version: "latest"
      - uses: technote-space/create-pr-action@91114507cf92349bec0a9a501c2edf1635427bc5 # 2.1.4
        with:
          EXECUTE_COMMANDS: |
            pip install -U pip-tools
            pip-compile --output-file=tests/testinfra/test-requirements.txt --upgrade tests/testinfra/test-requirements.in
            ./ci/update_versions.sh
          COMMIT_MESSAGE: "Upgrade versions files"
          COMMIT_NAME: "electrocucaracha bot"
          PR_BRANCH_NAME: "versions-update-${PR_ID}"
          PR_TITLE: "chore: update versions"
